### ISSUE TITLE
About the steps setting up Waveshare-7.9 from headless image

### ISSUE THREAD

**Issue by ocean1598** [project-owner/PeppyPlayers.doc#1]
Hi,

On my Pi4, I first installed the 7.9 inch image and it shows the splash screen then got stuck. I did not dig into why then I follow the steps: https://github.com/project-owner/PeppyPlayers.doc/wiki/Waveshare-7.9 then I got the blank screen.

Then I turn on the boot message and I can see boot messages, but to got stuck saying the input device doesn't exit. Then I checked the code seeing it's missing '/dev/input/touchscreen', but I only see '/dev/input/mice' on my Pi4. I suspect my 7.9 screen touchscreen doesn't work. The I see potential 2 discrepancies in the wiki from the code. So I'd like to check with you.

1. peppymeter.py uses '/dev/fb1' for framebuffer, but I only see '/dev/fb0'.
2. the wiki says 'sudo TSLIB_FBDEVICE=/dev/fb0 TSLIB_TSDEVICE=/dev/input/event0 ts_calibrate', both devices are different from the code.

Can you comment?

**Comment by project-owner** [comment]
Hi Edward,

I believe you are using the Pi 4 model. In this case you need to comment
out the following line in the file /boot/config.txt:
#dtoverlay=vc4-fkms-v3d
I updated the wiki page and mentioned this step for Pi 4. I should probably
do that for Pi3 images as well.

Regarding fb0/1. In the Peppy player I have the following logic:
https://github.com/project-owner/Peppy/blob/01fa75f3118192409459e130555cc4828be89e4a/util/config.py#L1323
I need to implement it in the PeppyMeter too. If you want to run the
stand-alone PeppyMeter you need to change fb1 to fb0 in the code.
In the disk images for the Waveshare 7.9" there is only fb0.

Best regards,
Gena.

**Comment by ocean1598** [comment]
Hi Gena,

Commenting out `#dtoverlay=vc4-fkms-v3d` works. The next thing I need to fix will be the touchscreen.
My touchscreen isn't been detected. Hence I don't see /dev/input/touchscreen or /dev/input/event0.

One more thing, is there a way to add more languages? I have Chinese music showing garbage on the album arts.

Ed

**Comment by project-owner** [comment]
This wiki page explains how to add new font/language:
https://github.com/project-owner/Peppy.doc/wiki/Languages
