### ISSUE TITLE
ssh password for images

### ISSUE THREAD

**Issue by kalingaa** [project-owner/PeppyPlayers.doc#2]
there is no username/password for images given, Eg: the 7" Official image  pi/Hogarth does not work. pi/raspberry does not work.

**Comment by project-owner** [comment]
Hi, if you loaded the image from this page: https://github.com/project-owner/PeppyPlayers.doc/wiki/Disk-Images
the current (June 25 2021) password is Monet.
If you loaded one of the previous images from this page: https://github.com/project-owner/Peppy/releases
then the password depends on edition which you loaded. For example for the previous version the password was Hiroshige.
